CC = g++
SRC_FILES = $(wildcard src/*.cpp)
OBJ_NAME = output
INCLUDE_PATHS = -I /Users/sameeragrawal/Downloads/eigen-3.4.0
COMPILER_FLAGS = -std=c++11 -Wall -O0 -g

all:
	$(CC) $(COMPILER_FLAGS) $(INCLUDE_PATHS) $(SRC_FILES) -o $(OBJ_NAME)